const money = value => new Intl.NumberFormat('en-US', {style:'currency', currency:'USD',maximumFractionDigits:0}).format(value || 0);
const date = value => new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${value}T12:00:00`));
const escape = text => String(text ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const total = values => values.reduce((sum,item) => sum + (+item.value || 0),0);
const gradient = values => { const sum=total(values)||1; let at=0; return values.map(item=>{const end=at+(item.value/sum)*100;const part=`${item.color} ${at}% ${end}%`;at=end;return part}).join(',') };
function renderBook(book){const pct=book.goalWords ? Math.min(100,book.wordCount/book.goalWords*100) : 0;const tiles=book.episodes.map(ep=>{const fill=Math.min(100,ep.words/3000*100);const body=`<b>${ep.number}</b><small>${ep.words.toLocaleString()} words</small>`;return ep.url?`<a class="episode" data-published="${ep.published}" style="--fill:${fill}%" href="/scenes/${ep.url.replace('./','')}">${body}</a>`:`<div class="episode" data-published="${ep.published}" style="--fill:${fill}%">${body}</div>`}).join('');return `<article class="book"><div class="book-top"><div><p class="book-label">${escape(book.arc)} · ${escape(book.label)}</p><h3>${escape(book.title)}</h3></div><p class="progress-copy">${book.wordCount.toLocaleString()} / ${(book.goalWords||0).toLocaleString()} words<br>${pct.toFixed(1)}% of book target</p></div><div class="progress"><span style="width:${pct}%"></span></div><div class="episodes">${tiles || '<p class="empty">The first pages are still on the bench.</p>'}</div></article>`}
function legend(title, values){const sum=total(values)||1;return `<div><p class="legend-title">${title}</p>${values.map(item=>`<div class="legend-row"><i style="background:${item.color}"></i><span>${escape(item.label)}</span><b>${Math.round(item.value/sum*100)}%</b></div>`).join('')}</div>`}
function init(data){document.title=`${data.siteTitle || 'The Workshop'} | Bloodline`;document.querySelector('#intro').textContent=data.intro||'';document.querySelector('#generated').textContent=data.generatedAt?`${data.updatedLabel||'Production ledger updated'} · ${date(data.generatedAt.slice(0,10))}`:'';document.querySelector('#books').innerHTML=data.books.map(renderBook).join('');const j=data.judahTotal||{};document.querySelector('#judah').innerHTML=j.amount?`<div class="damage-amount">${money(j.amount)}</div><p class="damage-copy">${j.incidents||0} recorded incident${j.incidents===1?'':'s'}${j.costliestEpisode?` · costliest: Episode ${j.costliestEpisode}`:''}</p>`:'<p class="empty">The public ledger is waiting for its first fully approved tally.</p>';document.querySelector('#drops').innerHTML=data.nextDrops?.length?`<ul class="drops-list">${data.nextDrops.map(drop=>`<li><time>${date(drop.date)}</time><span>${escape(drop.label)}${drop.url?` · <a href="${escape(drop.url)}">read</a>`:''}</span></li>`).join('')}</ul>`:'<p class="empty">No public dates are on the calendar yet. When they are, they’ll appear here.</p>';const tone=data.tone||{},genre=tone.genre||[],mood=tone.mood||[];document.querySelector('#tone').innerHTML=total(genre)||total(mood)?`<div class="rings" data-label="${(tone.episodes||[]).length} EPISODES\nSCORED" style="--segments:${gradient(genre)};--moods:${gradient(mood)}"></div><div class="legends">${legend('Genre · outer ring',genre)}${legend('Tone · inner ring',mood)}</div>${tone.episodes?.length?`<div class="episode-mix">${tone.episodes.map(ep=>`<div class="mix-bar" title="Episode ${ep.number}" style="--colors:${gradient(ep.genre||[])}"></div>`).join('')}</div>`:''}`:'<p class="empty">The scoring ledger is being prepared. It will show the episode-by-episode genre and tonal drift once those public scores are approved.</p>';document.querySelector('#inventory').innerHTML=data.worldInventory?.length?data.worldInventory.map(item=>`<div><strong>${item.count}</strong>${escape(item.label)}</div>`).join(''):'<p class="empty">Inventory will be added as public entries are approved.</p>';document.querySelector('#activity').innerHTML=(data.activity||[]).map(item=>`<li><time>${date(item.date)}</time><span>${escape(item.label)}</span></li>`).join('')||'<li><span>Nothing new to file just yet.</span></li>'}
fetch('/content/workshop.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw Error('Workshop data unavailable');return response.json()}).then(init).catch(()=>{document.querySelector('#generated').textContent='The ledger is temporarily unavailable. Please check back shortly.'});
